In [1]:
import sagemaker
import pandas as pd

In [2]:
sess = sagemaker.Session()

In [3]:
%store -r bucket

In [4]:
import botocore
from datasets.filesystems import S3FileSystem
from datasets import load_from_disk

s3_session = botocore.session.Session()
s3 = S3FileSystem(session=s3_session)
dataset = load_from_disk(f's3://{bucket}/processing_output/train_data/', fs=s3)

In [5]:
df_train = pd.DataFrame(dataset)

In [6]:
df_train.head(10)

,__index_level_0__,attention_mask,input_ids,label,text,token_type_ids
0,6260,"[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, ...","[101, 8292, 21890, 2571, 20303, 23438, 1999, 1...",1,Cephalexin rash in infectious mononucleosis.,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
1,2344,"[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[101, 7863, 1024, 2000, 6235, 1037, 2553, 1997...",1,OBJECTIVE: To describe a case of exacerbated m...,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
2,4915,"[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[101, 24534, 3350, 1997, 2014, 10374, 23350, 8...",1,Autopsy evidence of herpesvirus infection was ...,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
3,17320,"[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[101, 2023, 3189, 5577, 2176, 5022, 2007, 8349...",0,This report describes four patients with varia...,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
4,14049,"[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[101, 7020, 16344, 2475, 2050, 2001, 2036, 522...",0,SSTR2A was also expressed in lymphocytes that ...,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
5,3889,"[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[101, 15306, 1024, 17371, 1011, 13323, 1998, 2...",1,CONCLUSIONS: SD-OCT and AO detected abnormalit...,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
6,7060,"[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[101, 4483, 6074, 2031, 2146, 2042, 2245, 2000...",0,Environmental agents have long been thought to...,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
7,7753,"[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[101, 2053, 11594, 4839, 2005, 20177, 21656, 2...",0,No guidelines exist for calculating doses by e...,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
8,10133,"[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, ...","[101, 4725, 1024, 15354, 5486, 2512, 9006, 286...",0,METHODS: Retrospective consecutive noncomparat...,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
9,13298,"[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[101, 11325, 1048, 24335, 8458, 16429, 28723, ...",0,Acute lymphoblastic leukemia in a patient with...,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."

In [9]:
import pandas as pd
from pandas import option_context

with option_context("display.max_rows", None,"display.max_colwidth",60,"display.max_columns",50):
        display(df_train.head(10))

,__index_level_0__,attention_mask,input_ids,label,text,token_type_ids
0,6260,"[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0...","[101, 8292, 21890, 2571, 20303, 23438, 1999, 16514, 1884...",1,Cephalexin rash in infectious mononucleosis.,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0..."
1,2344,"[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1...","[101, 7863, 1024, 2000, 6235, 1037, 2553, 1997, 4654, 10...",1,OBJECTIVE: To describe a case of exacerbated mania poten...,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0..."
2,4915,"[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1...","[101, 24534, 3350, 1997, 2014, 10374, 23350, 8985, 2001,...",1,Autopsy evidence of herpesvirus infection was found in v...,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0..."
3,17320,"[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1...","[101, 2023, 3189, 5577, 2176, 5022, 2007, 8349, 17076, 3...",0,This report describes four patients with variant angina ...,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0..."
4,14049,"[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1...","[101, 7020, 16344, 2475, 2050, 2001, 2036, 5228, 1999, 1...",0,SSTR2A was also expressed in lymphocytes that had infilt...,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0..."
5,3889,"[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1...","[101, 15306, 1024, 17371, 1011, 13323, 1998, 20118, 1115...",1,CONCLUSIONS: SD-OCT and AO detected abnormalities that c...,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0..."
6,7060,"[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1...","[101, 4483, 6074, 2031, 2146, 2042, 2245, 2000, 2022, 57...",0,Environmental agents have long been thought to be linked...,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0..."
7,7753,"[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1...","[101, 2053, 11594, 4839, 2005, 20177, 21656, 2011, 2593,...",0,No guidelines exist for calculating doses by either actu...,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0..."
8,10133,"[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0...","[101, 4725, 1024, 15354, 5486, 2512, 9006, 28689, 6024, ...",0,METHODS: Retrospective consecutive noncomparative case s...,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0..."
9,13298,"[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1...","[101, 11325, 1048, 24335, 8458, 16429, 28723, 25468, 199...",0,Acute lymphoblastic leukemia in a patient with chronic c...,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0..."

In [7]:
df_train['label'].sum()/len(df_train)

0.2079031927257811

In [10]:
df_train.iloc[0]

__index_level_0__                                                 6260
attention_mask       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, ...
input_ids            [101, 8292, 21890, 2571, 20303, 23438, 1999, 1...
label                                                                1
text                      Cephalexin rash in infectious mononucleosis.
token_type_ids       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
Name: 0, dtype: object